### ISSUE TITLE
Total ETA does not take into account parallelism

### ISSUE THREAD

**Issue by JavierGOrdonnez** [ITISFoundation/osparc-meta-parallelrunner#11]
Small bug I found wrt the ETA functionality - the total displayed on top does not take into account how many workers (N) are running in parallel. Thus, it drops by N seconds every second, and provides an estimate which is N times the real estimate. Should be easy to fix. Thanks.

![image](https://github.com/user-attachments/assets/b3143bcc-69c6-4e6c-b5bc-1b167c1187d3)

**Comment by wvangeit** [comment]
Yeah, i knew that, still had to improve that, thx for reporting. The issue was that my task information file doesn't know how many workers there are, will have to change that file format a bit.

**Comment by wvangeit** [comment]
A fix is being deployed as version 1.1.9 of PR. 
Let me know in case you see similar issues.
