### ISSUE TITLE
Outputs of ParallelRunner are deleted on closing & opening the study

### ISSUE THREAD

**Issue by JavierGOrdonnez** [ITISFoundation/osparc-meta-parallelrunner#12]
Current behaviour
---
The outputs of the Parallel Runner are completely reseted when the study is closed / crashes (e.g. back to dashboard) and then opened again.

This means the resulting "output_tasks.json" file will be completely lost (and thus the Parallel Run will be wasted) if the unaware user goes out of the study (e.g. end-of-workday, or accidentally closing the browser window) and then goes in again to extract and process the output data.

Desired behaviour 
---
cleanup of output dir of the Parallel Runner only happens on new run

**Comment by wvangeit** [comment]
myeah, interesting problem. The reason why these are deleted is not to confuse the calling process with the old run being present. 
I guess I could change that now though, since the tasks now have unique ids, so in theory the caller can recognize old files. I only puts some trust on the calling process to be 'smart' enough about it :-)

**Comment by wvangeit** [comment]
btw, if things crash atm, there normally would be no output_tasks.json, because it's only written when all the tasks come back.

**Comment by JavierGOrdonnez** [comment]
I meant things like browser crash / accidental reload (or simply unawareness of this issue). 

I would agree that a new run should eliminate the old results. However, without running (simply loading the interactive service) results should still be there. This is in agreement with the behaviour of purely computational services - outputs are available until a new run is created.

One option would be to move the outputs to a different output of the service (and keep the handshake in output1, which is cleant on service startup).

**Comment by wvangeit** [comment]
I have deployed version 1.1.8 on osparc. This version will delete the previous outputs only right before a new task run starts.

(But please don't start to depend on this behavior, once the clients of PR become more mature, this behavior would disappear again to avoid reproducibility issues)
